services:
    abexplorer:
      extends:
        file: docker-compose.yml
        service: abexplorer
      environment:
        - BLOCK_EXPLORER_NODES_0_URL=https://tokens-archive-pentest.testnet.alphabill.org/rpc
        - BLOCK_EXPLORER_NODES_0_BLOCK_NUMBER=2
        - BLOCK_EXPLORER_NODES_1_URL=
        - BLOCK_EXPLORER_NODES_1_BLOCK_NUMBER=
        - BLOCK_EXPLORER_LOG_LEVEL=DEBUG

    mongo:
      extends:
        file: docker-compose.yml
        service: mongo

volumes:
  mongo-data: