basePath: /api/v1
definitions:
  domain.Bill:
    properties:
      counter:
        type: integer
      id:
        items:
          type: integer
        type: array
      lockStatus:
        type: integer
      networkID:
        $ref: '#/definitions/types.NetworkID'
      partitionID:
        type: integer
      value:
        type: integer
    type: object
  restapi.BlockInfo:
    properties:
      blockNumber:
        type: integer
      partitionID:
        type: integer
      partitionTypeID:
        type: integer
      previousBlockHash:
        items:
          type: integer
        type: array
      proposerID:
        type: string
      shardID:
        $ref: '#/definitions/types.ShardID'
      txHashes:
        items:
          items:
            type: integer
          type: array
        type: array
      unicityCertificate:
        items:
          type: integer
        type: array
    type: object
  restapi.BlockResponse:
    additionalProperties:
      $ref: '#/definitions/restapi.BlockInfo'
    type: object
  restapi.ErrorResponse:
    properties:
      message:
        type: string
    type: object
  restapi.SearchResponse:
    properties:
      blocks:
        additionalProperties:
          $ref: '#/definitions/restapi.BlockInfo'
        type: object
      txs:
        items:
          $ref: '#/definitions/restapi.TxInfo'
        type: array
    type: object
  restapi.TxInfo:
    properties:
      blockNumber:
        type: integer
      partitionID:
        type: integer
      transaction:
        $ref: '#/definitions/types.TransactionRecord'
      txOrderHash:
        items:
          type: integer
        type: array
      txRecordHash:
        items:
          type: integer
        type: array
    type: object
  service.PartitionRoundInfo:
    properties:
      epochNumber:
        type: integer
      partitionID:
        type: integer
      partitionTypeID:
        type: integer
      roundNumber:
        type: integer
    type: object
  types.NetworkID:
    enum:
    - 1
    - 2
    - 3
    type: integer
    x-enum-varnames:
    - NetworkMainNet
    - NetworkTestNet
    - NetworkLocal
  types.ServerMetadata:
    properties:
      actualFee:
        type: integer
      processingDetails:
        items:
          type: integer
        type: array
      successIndicator:
        $ref: '#/definitions/types.TxStatus'
      targetUnits:
        items:
          items:
            type: integer
          type: array
        type: array
    type: object
  types.ShardID:
    type: object
  types.TransactionRecord:
    properties:
      serverMetadata:
        $ref: '#/definitions/types.ServerMetadata'
      transactionOrder:
        items:
          type: integer
        type: array
      version:
        type: integer
    type: object
  types.TxStatus:
    enum:
    - 0
    - 1
    - 2
    type: integer
    x-enum-varnames:
    - TxStatusFailed
    - TxStatusSuccessful
    - TxErrOutOfGas
info:
  contact: {}
  description: API to query blocks and transactions of Alphabill
  title: Alphabill Blockchain Explorer API
  version: "1.0"
paths:
  /address/{pubKey}/bills:
    get:
      consumes:
      - application/json
      description: Get bills associated with a specific public key
      parameters:
      - description: Public Key
        in: path
        name: pubKey
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: List of bills
          schema:
            items:
              $ref: '#/definitions/domain.Bill'
            type: array
        "400":
          description: 'Error: Missing ''pubKey'' variable in the URL'
          schema:
            $ref: '#/definitions/restapi.ErrorResponse'
        "404":
          description: 'Error: Bills with specified public key not found'
          schema:
            $ref: '#/definitions/restapi.ErrorResponse'
      summary: Retrieve bills by public key
      tags:
      - Bills
  /blocks/{blockNumber}:
    get:
      consumes:
      - application/json
      description: Retrieves a block for all given partitions by using the provided
        block number as a path parameter, or retrieves the latest block if no number
        is specified.
      parameters:
      - description: Block number ('latest' or a specific number)
        in: path
        name: blockNumber
        required: true
        type: string
      - description: List of partitions to get the blocks for. If not provided then
          get for all partitions
        in: query
        name: partitionID
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Block information successfully retrieved
          schema:
            $ref: '#/definitions/restapi.BlockResponse'
        "400":
          description: Missing or invalid block number
          schema:
            type: string
        "404":
          description: No block found with the specified number
          schema:
            type: string
        "500":
          description: Internal server error, such as a failure to retrieve the block
          schema:
            type: string
      summary: Retrieve a blockchain block by number, or the latest if unspecified
      tags:
      - Blocks
  /partitions/{partitionID}/blocks:
    get:
      description: Get blocks in a single partition, given a start block number and
        limit.
      parameters:
      - description: Partition ID to get the blocks for
        in: path
        name: partitionID
        required: true
        type: string
      - description: optionally specify the start block number
        in: query
        name: startBlock
        type: string
      - description: optionally specify the number of blocks to return, defaults to
          10
        in: query
        name: limit
        type: string
      - description: whether to include blocks without transactions, defaults to true
        in: query
        name: includeEmpty
        type: boolean
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/restapi.BlockInfo'
            type: array
      summary: Get blocks in a single partition, given a start block number and limit.
      tags:
      - Blocks
  /partitions/{partitionID}/blocks/{blockNumber}/txs:
    get:
      consumes:
      - application/json
      description: Retrieves a list of transactions for a given block number.
      parameters:
      - description: Partition ID to get the transactions for
        in: path
        name: partitionID
        required: true
        type: integer
      - description: The block number for which to retrieve transactions
        in: path
        name: blockNumber
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Successfully retrieved list of transactions for the block
          schema:
            items:
              $ref: '#/definitions/restapi.TxInfo'
            type: array
        "400":
          description: Missing or invalid 'blockNumber' variable in the URL
          schema:
            type: string
        "404":
          description: No transactions found for the specified block number
          schema:
            type: string
      summary: Retrieve transactions by block number
      tags:
      - Transactions
  /partitions/{partitionID}/txs:
    get:
      description: Retrieves a list of transactions.
      parameters:
      - description: Partition ID to get the transactions for
        in: path
        name: partitionID
        required: true
        type: string
      - description: ID of the transaction to start from, if not provided, the latest
          transactions are returned
        in: query
        name: startID
        type: string
      - description: The maximum number of transactions to retrieve, default 20
        in: query
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Successfully retrieved list of transactions
          schema:
            items:
              $ref: '#/definitions/restapi.TxInfo'
            type: array
      summary: Retrieve transactions, latest first.
      tags:
      - Transactions
  /round-number:
    get:
      description: Retrieve round and epoch number for each partition
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/service.PartitionRoundInfo'
            type: array
      summary: Retrieve round and epoch number for each partition
      tags:
      - Info
  /search:
    get:
      description: Retrieve blocks and transactions matching the search key
      parameters:
      - description: Search key
        in: query
        name: q
        required: true
        type: string
      - description: Filter results by partition ID(s)
        in: query
        name: partitionID
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Block information successfully retrieved
          schema:
            $ref: '#/definitions/restapi.SearchResponse'
        "400":
          description: invalid partitionID
          schema:
            type: string
        "404":
          description: no results found
          schema:
            type: string
      summary: Retrieve blocks and transactions matching the search key
      tags:
      - Search
  /txs/{txHash}:
    get:
      consumes:
      - application/json
      description: Retrieves transaction details using a transaction hash provided
        as a path parameter.
      parameters:
      - description: The hash of the transaction to retrieve (HEX encoded)
        in: path
        name: txHash
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Successfully retrieved the transaction information
          schema:
            $ref: '#/definitions/restapi.TxInfo'
        "400":
          description: Missing 'txHash' variable in the URL
          schema:
            type: string
        "404":
          description: Transaction with the specified hash not found
          schema:
            type: string
        "500":
          description: Failed to load transaction details
          schema:
            type: string
      summary: Retrieve a transaction by hash
      tags:
      - Transactions
  /units/{unitID}/txs:
    get:
      consumes:
      - application/json
      description: Get transactions associated with a specific unit ID
      parameters:
      - description: Unit ID (0xHEX encoded)
        in: path
        name: unitID
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: List of transactions
          schema:
            items:
              $ref: '#/definitions/restapi.TxInfo'
            type: array
        "400":
          description: 'Error: Missing ''unitID'' variable in the URL'
          schema:
            $ref: '#/definitions/restapi.ErrorResponse'
        "404":
          description: 'Error: Transaction with specified unit ID not found'
          schema:
            $ref: '#/definitions/restapi.ErrorResponse'
      summary: Retrieve transactions by unit ID
      tags:
      - Transactions
swagger: "2.0"
