nodes:
  - "dev-ab-money-archive.abdev1.guardtime.com/rpc"
  - "dev-ab-tokens-archive.abdev1.guardtime.com/rpc"

db:
  url: "mongodb://localhost:27017"

server:
  address: "localhost:9666"

block_number: 1
